#!/bin/sh

# =========================================================================
#
#	createRegSSL
#
#	  Shell script to create SSL certificates for the docker registry, using default
#       values, and exit.
#
# =========================================================================
#
# @author Jay Wheeler.
# @version 0.0.1
# @copyright © 2017. EarthWalk Software.
# @license Licensed under the Academic Free License version 3.0
# @package alpine-registry-ssl
# @subpackage registrySSL
#
# =========================================================================

# =========================================================================
#
#	Copyright © 2017. EarthWalk Software
#	Licensed under the Academic Free License, version 3.0.
#
#	Refer to the file named License.txt provided with the source,
#	or from
#
#		http://opensource.org/licenses/academic.php
#
# =========================================================================

docker run --rm \
           --name=regssl 
           -it \
           -e REG_DOMAIN=localhost.lan:5000 \
           -v $HOME/.certs:/crts \
           -v /etc/docker/certs.d:/docker \
           -v $HOME/bin:/regbin
       earthwalksoftware/regssl:latest

# =========================================================================
